set_property -dict {PACKAGE_PIN T21 IOSTANDARD LVCMOS33} [get_ports GPIO_0_tri_io[0]]
set_property -dict {PACKAGE_PIN R18 IOSTANDARD LVCMOS25} [get_ports irq]
set_property -dict {PACKAGE_PIN R16 IOSTANDARD LVCMOS25} [get_ports in2]

set_property LOC G17 [get_ports USB_PULLUP]
set_property IOSTANDARD LVCMOS25 [get_ports USB_PULLUP]


#pl GCLK 100MHz
set_property -dict {PACKAGE_PIN Y9 IOSTANDARD LVCMOS33} [get_ports pl_gclk]

set_property -dict {PACKAGE_PIN T22 IOSTANDARD LVCMOS33} [get_ports led0]
#set_property -dict {PACKAGE_PIN T21 IOSTANDARD LVCMOS33} [get_ports led1]
set_property -dict {PACKAGE_PIN U22 IOSTANDARD LVCMOS33} [get_ports led2]
set_property -dict {PACKAGE_PIN U21 IOSTANDARD LVCMOS33} [get_ports led3]
set_property -dict {PACKAGE_PIN V22 IOSTANDARD LVCMOS33} [get_ports led4]
set_property -dict {PACKAGE_PIN W22 IOSTANDARD LVCMOS33} [get_ports led5]
set_property -dict {PACKAGE_PIN U19 IOSTANDARD LVCMOS33} [get_ports led6]
set_property -dict {PACKAGE_PIN U14 IOSTANDARD LVCMOS33} [get_ports led7]

set_property -dict {PACKAGE_PIN F22 IOSTANDARD LVCMOS25} [get_ports SW0]
set_property -dict {PACKAGE_PIN G22 IOSTANDARD LVCMOS25} [get_ports SW1]
set_property -dict {PACKAGE_PIN H22 IOSTANDARD LVCMOS25} [get_ports SW2]
set_property -dict {PACKAGE_PIN F21 IOSTANDARD LVCMOS25} [get_ports SW3]
set_property -dict {PACKAGE_PIN H19 IOSTANDARD LVCMOS25} [get_ports SW4]
set_property -dict {PACKAGE_PIN H18 IOSTANDARD LVCMOS25} [get_ports SW5]
set_property -dict {PACKAGE_PIN H17 IOSTANDARD LVCMOS25} [get_ports SW6]
set_property -dict {PACKAGE_PIN M15 IOSTANDARD LVCMOS25} [get_ports SW7]

set_property -dict {PACKAGE_PIN N15 IOSTANDARD LVCMOS25} [get_ports BUTTON1]
set_property -dict {PACKAGE_PIN T18 IOSTANDARD LVCMOS25} [get_ports BUTTON2]
set_property -dict {PACKAGE_PIN P16 IOSTANDARD LVCMOS25} [get_ports BUTTON3]
#set_property -dict {PACKAGE_PIN R16 IOSTANDARD LVCMOS25} [get_ports BUTTON4]
#set_property -dict {PACKAGE_PIN R18 IOSTANDARD LVCMOS25} [get_ports BUTTON5]

# ad9361
set_property PACKAGE_PIN F18 [get_ports spi_csn]
set_property IOSTANDARD LVCMOS25 [get_ports spi_csn]
set_property PULLUP true [get_ports spi_csn]
set_property -dict {PACKAGE_PIN E18 IOSTANDARD LVCMOS25} [get_ports spi_clk]
set_property -dict {PACKAGE_PIN E21 IOSTANDARD LVCMOS25} [get_ports spi_sdo]
set_property -dict {PACKAGE_PIN D21 IOSTANDARD LVCMOS25} [get_ports spi_sdi]
set_property -dict {PACKAGE_PIN G15 IOSTANDARD LVCMOS25} [get_ports en_agc]
set_property -dict {PACKAGE_PIN G16 IOSTANDARD LVCMOS25} [get_ports sync_in]
set_property -dict {PACKAGE_PIN A16 IOSTANDARD LVCMOS25} [get_ports resetb]
set_property -dict {PACKAGE_PIN J20 IOSTANDARD LVCMOS25} [get_ports enable]
set_property -dict {PACKAGE_PIN K21 IOSTANDARD LVCMOS25} [get_ports txnrx]
set_property -dict {PACKAGE_PIN A18 IOSTANDARD LVCMOS25} [get_ports {ctrl_in[0]}]
set_property -dict {PACKAGE_PIN A19 IOSTANDARD LVCMOS25} [get_ports {ctrl_in[1]}]
set_property -dict {PACKAGE_PIN D22 IOSTANDARD LVCMOS25} [get_ports {ctrl_in[2]}]
set_property -dict {PACKAGE_PIN C22 IOSTANDARD LVCMOS25} [get_ports {ctrl_in[3]}]
set_property -dict {PACKAGE_PIN G20 IOSTANDARD LVCMOS25} [get_ports {ctrl_out[0]}]
set_property -dict {PACKAGE_PIN G21 IOSTANDARD LVCMOS25} [get_ports {ctrl_out[1]}]
set_property -dict {PACKAGE_PIN E19 IOSTANDARD LVCMOS25} [get_ports {ctrl_out[2]}]
set_property -dict {PACKAGE_PIN E20 IOSTANDARD LVCMOS25} [get_ports {ctrl_out[3]}]
set_property -dict {PACKAGE_PIN G19 IOSTANDARD LVCMOS25} [get_ports {ctrl_out[4]}]
set_property -dict {PACKAGE_PIN F19 IOSTANDARD LVCMOS25} [get_ports {ctrl_out[5]}]
set_property -dict {PACKAGE_PIN E15 IOSTANDARD LVCMOS25} [get_ports {ctrl_out[6]}]
set_property -dict {PACKAGE_PIN D15 IOSTANDARD LVCMOS25} [get_ports {ctrl_out[7]}]

set_property -dict {PACKAGE_PIN M19 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports rx_clk_in_p]
set_property -dict {PACKAGE_PIN M20 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports rx_clk_in_n]
set_property -dict {PACKAGE_PIN N19 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports rx_frame_in_p]
set_property -dict {PACKAGE_PIN N20 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports rx_frame_in_n]
set_property -dict {PACKAGE_PIN P17 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_p[0]}]
set_property -dict {PACKAGE_PIN P18 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_n[0]}]
set_property -dict {PACKAGE_PIN N22 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_p[1]}]
set_property -dict {PACKAGE_PIN P22 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_n[1]}]
set_property -dict {PACKAGE_PIN M21 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_p[2]}]
set_property -dict {PACKAGE_PIN M22 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_n[2]}]
set_property -dict {PACKAGE_PIN J18 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_p[3]}]
set_property -dict {PACKAGE_PIN K18 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_n[3]}]
set_property -dict {PACKAGE_PIN L21 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_p[4]}]
set_property -dict {PACKAGE_PIN L22 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_n[4]}]
set_property -dict {PACKAGE_PIN T16 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_p[5]}]
set_property -dict {PACKAGE_PIN T17 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_n[5]}]
set_property -dict {PACKAGE_PIN J21 IOSTANDARD LVDS_25} [get_ports tx_clk_out_p]
set_property -dict {PACKAGE_PIN J22 IOSTANDARD LVDS_25} [get_ports tx_clk_out_n]
set_property -dict {PACKAGE_PIN R20 IOSTANDARD LVDS_25} [get_ports tx_frame_out_p]
set_property -dict {PACKAGE_PIN R21 IOSTANDARD LVDS_25} [get_ports tx_frame_out_n]
set_property -dict {PACKAGE_PIN N17 IOSTANDARD LVDS_25} [get_ports {tx_data_out_p[0]}]
set_property -dict {PACKAGE_PIN N18 IOSTANDARD LVDS_25} [get_ports {tx_data_out_n[0]}]
set_property -dict {PACKAGE_PIN P20 IOSTANDARD LVDS_25} [get_ports {tx_data_out_p[1]}]
set_property -dict {PACKAGE_PIN P21 IOSTANDARD LVDS_25} [get_ports {tx_data_out_n[1]}]
set_property -dict {PACKAGE_PIN L17 IOSTANDARD LVDS_25} [get_ports {tx_data_out_p[2]}]
set_property -dict {PACKAGE_PIN M17 IOSTANDARD LVDS_25} [get_ports {tx_data_out_n[2]}]
set_property -dict {PACKAGE_PIN R19 IOSTANDARD LVDS_25} [get_ports {tx_data_out_p[3]}]
set_property -dict {PACKAGE_PIN T19 IOSTANDARD LVDS_25} [get_ports {tx_data_out_n[3]}]
set_property -dict {PACKAGE_PIN K19 IOSTANDARD LVDS_25} [get_ports {tx_data_out_p[4]}]
set_property -dict {PACKAGE_PIN K20 IOSTANDARD LVDS_25} [get_ports {tx_data_out_n[4]}]
set_property -dict {PACKAGE_PIN J16 IOSTANDARD LVDS_25} [get_ports {tx_data_out_p[5]}]
set_property -dict {PACKAGE_PIN J17 IOSTANDARD LVDS_25} [get_ports {tx_data_out_n[5]}]


set_false_path -from [get_clocks clk_fpga_0] -to [get_clocks clk_fpga_0]